version: '3.7'

services:
  app:
    build: src
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - ./src:/app
      - ./src/migrations:/app/migrations
    restart: on-failure
    environment:
      - FLASK_ENV
    depends_on:
      - nginx
      - redis
      - postgres
    networks:
      - myNet

  nginx:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - myNet

  redis:
    image: "redis:alpine"
    networks:
      - myNet

  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/articles/pgdata
    env_file:
      - .env
    user: $USER_ID:$GROUP_ID
    networks:
      - myNet

networks:
  myNet: