version: '3.7'

services:
  backend:
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: sh -c "npm i && npm run build"
