version: '3.7'

services:
  backend:
    environment:
      - FLASK_ENV=production

  frontend:
    build: frontend

  proxy:
    build: proxy
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    depends_on:
      - backend
    networks:
      - blog_net
