version: '3'
services:
  app:
    working_dir: /app
    build: src
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
      - ./src/migrations:/app/migrations
    restart: on-failure
    depends_on:
      - redis
      - postgres
    environment:
      FLASK_ENV: development
    networks:
      - someNet

  redis:
    image: "redis:alpine"
    networks:
      - someNet

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    user: $USER_ID:$GROUP_ID
    networks:
      - someNet

networks:
  someNet: