// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'FileLoader': string;
  'FileLoader__img': string;
  'FileLoader__input': string;
  'FileLoader__label': string;
}
export const cssExports: CssExports;
export default cssExports;
