// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Сreator': string;
  'Сreator__cover': string;
  'Сreator__description': string;
  'Сreator__field': string;
  'Сreator__footer': string;
  'Сreator__section': string;
  'Сreator__tags': string;
  'Сreator__text': string;
  'Сreator__title': string;
}
export const cssExports: CssExports;
export default cssExports;
